### ISSUE TITLE
Import DDLs

### ISSUE THREAD

**Issue by yapnel** [teiid/teiid#1258]
Hi

I have two DDL VDBs and i want to incorporate it into the main VDB. Is there a way to do this please? Kindly give an example for the full syntax.

Thanks

**Comment by yapnel** [comment]
This is how i have done in the main VDB importing two DDL VDBs. When i deploy this on Wildfly it throws error. Any advise? Thanks

> Cannot upload deployment: {"WFLYCTL0080: Failed services" => {"jboss.teiid.vdb.nc.1" => "org.teiid.deployers.VirtualDatabaseException: TEIID40093 Model NC_Source specified with no source information in VDB nc.1 Caused by: org.teiid.deployers.VirtualDatabaseException: TEIID40093 Model NC_Source specified with no source information in VDB nc.1"}}




> CREATE DATABASE nc VERSION '1';
USE DATABASE nc VERSION '1';
--############ Schemas ############
CREATE SCHEMA NC_Source;
--############ Schema:NC_Source ############
SET SCHEMA NC_Source;
IMPORT FROM REPOSITORY "DDL-FILE" INTO NC_Source OPTIONS ("ddl-file" '/yahoo-vdb.ddl');
IMPORT FROM REPOSITORY "DDL-FILE" INTO NC_Source OPTIONS ("ddl-file" '/githubcovid-vdb.ddl');

**Comment by yapnel** [comment]
Also how do i package the 3 files to deploy into Wildfly?

**Comment by rareddy** [comment]
You still need to define and configure your sources, individually these VDBs need to be deployed on their own before they can be imported into the main VDB.

> Also how do i package the 3 files to deploy into Wildfly?
Each VDB is deployed on its own it is not packaged into a single artifact. At *runtime* the main VDB will read metadata from other two VDBs to form a final vdb.

Please also note this model changes when working with the VDBs in the OpenShift Operator model, there you need to use VDBs as maven artifacts to work with import feature. Here you need to build the each VDB as Maven artifact, a maven plugin is provided for your development. The main VDB is supplied with co-ordinates of other two VDBs in its DDL then the maven plugin  will import the metadata from the other two VDBs at *build* time to form the main vdb. Since the import here happening at build time, one needs to practice caution as if you are `IMPORT FOREIGN SCHEMA` statements they will be resolved until VDB is deployed, thus any ALTER/DROP statements in DDL are not supported. I added some language around this here https://github.com/teiid/teiid-openshift-examples/blob/master/dv-on-openshift.adoc#virtualdatabase-ddl-limitations
