### ISSUE TITLE
maxFileStoreLength calculation

### ISSUE THREAD

**Issue by codernaut** [teiid/teiid#1314]
In teiid 12.x we are calculating as follows:

long max = this.storageManager.getMaxStorageSpace();
            this.maxFileStoreLength  = (max/maxActivePlans)>>2;

in BufferManagerImpl

max/maxactiveplans make sense.

But why are we shifting by 2 ?

**Comment by shawkins** [comment]
> But why are we shifting by 2 ?

Originally that was to further limit where resource consumption may be getting out of hand as you can create any number of temporary files per plan.  So rather than allow for example a single sqlxml intermediate result to consume up to proportional plan limit, each is allowed a quarter of that space.

This logic has since been complimented, or even superseded, by TEIID-5584.  If you are seeing an issue where that limit is too restrictive it would be fine to relax it or make it configurable as memory consumption is tracked by session and the session consuming the largest amount will be killed on an out of memory event.

**Comment by codernaut** [comment]
Thanks @shawkins so this means for 25 gb lob with default 20 action plans we should set that maxstoragesapce as 1.5 tb ?

Next question would be is this only for lob being used at run time or teiid accumulate previous data and does lazy cleanup ?

**Comment by shawkins** [comment]
> Thanks @shawkins so this means for 25 gb lob with default 20 action plans we should set that maxstoragesapce as 1.5 tb ?

2 tb would be the current workaround.  I'll log a jira to relax that limit based upon TEIID-5584.

> Next question would be is this only for lob being used at run time or teiid accumulate previous data and does lazy cleanup ?

Temporary files/lobs are generally cleaned up as early as possible.  There is also cleanup associated when a query completes and vm reference tracking to cleanup everything else.

**Comment by codernaut** [comment]
Thanks will do for our purpose
