### ISSUE TITLE
Parsing Non Fixed JSON Attributes

### ISSUE THREAD

**Issue by yapnel** [teiid/teiid#1321]
Hi,

I have an REST endpoint that returns a JSON with different structure depending on what data is available in the endpoint system. I have a query using JSONTABLE to parse the JSON object with defined path to the attributes. The query fails sometimes because the attribute is not available in the JSON. Is there a way to handle not available attribute path in the parsing of the JSON object?

Example below i have defined the path for website but the return JSON from the endpoint doesn't have website attribute defined depending on the parameter submitted in the request

`select
  g.*
from 
JSONTABLE
(
  '{
  "name": "National Westminster Bank"
  }',
  '$' COLUMNS
  "name" string path '@["name"]',
  "website" string path '@["website"]'
) as g;
`

Many thanks

**Comment by shawkins** [comment]
Have you tried the optional boolean argument nullLeafOnMissing on jsontable http://teiid.github.io/teiid-documents/master/content/reference/r_jsontable.html

**Comment by yapnel** [comment]
After adding TRUE the website column is returning NULL which is correct. However, when i do the below, i expect ticker column to return null too but it is throwing an error. Any idea why?

`select
g.*
from JSONTABLE
(
   '{ 
    "name": "National Westminster Bank"
    }',
   '$',True 
   COLUMNS "name" string path '@["name"]',
   "website" string path '@["website"]',
   "ticker" string path '@["stock"]["ticker"]'
)
as g;`

**Comment by shawkins** [comment]
It's because stock doesn't exist either.  JSONPath has some ambiguity around this handling in it's implementations.  In this jayway implementation the only way to get that behavior is to specify a "suppress exceptions" option, which would mask other issues.

You should be able to workaround with something like:

`select g.name, g.website, jsonpathvalue(g.stock, '$.ticker', true) from JSONTABLE ( '{ "name": "National Westminster Bank", "stock":{"ticker":"abc"} }', '$',True COLUMNS "name" string path '@["name"]', "website" string path '@["website"]', "stock" string path '@["stock"]' ) as g;`

where you post process the ticker from the stock - if it exists.  However I can see that the jayway implementation is inconsistent in how it returns those single values, so we actually get a HashMap which gets converted to an invalid json string.  I'll address this with https://issues.redhat.com/browse/TEIID-6018

An issue could be captured as well for handling of intermediate properties, but it appears that question has been asked over the years in a couple of forms and jayway is no longer maintained.

The only other thing you could do would look like:

`select g.name, g.website, case when length(g.ticker) > 2 then jsonpathvalue(g.ticker, '$[0]', true) end  from JSONTABLE ( '{ "name": "National Westminster Bank", "x":1, "stock":{"ticker":"abc"} }', '$',True COLUMNS "name" string path '@["name"]', "website" string path '@["website"]', "ticker" string path '@..stock..ticker' ) as g;`

By using an indefinite path for the ticker it returns a json array string that unfortunately we have to test for emptiness as null.
