### ISSUE TITLE
ENV_VAR

### ISSUE THREAD

**Issue by yapnel** [teiid/teiid#1330]
Where and how do I set the env variables? Can I use this function inside virtual stored procedure and view?

Thanks

**Comment by shawkins** [comment]
There isn't currently a function for setting environment variables, only getting them.  Also there isn't a Java built-in way to set env variables, so if you add a UDF it would need platform dependent code.  Otherwise the expectation is that the variables are set prior to the launch of the java process.

**Comment by yapnel** [comment]
So, I have secrets defined in the http rest as authorization header. I don't want to expose this inside the virtual view. What is the best way to safely store it?

**Comment by shawkins** [comment]
> What is the best way to safely store it?

Why/how are they exposed in a view?
